### ISSUE TITLE
No responsive classes for container

### ISSUE THREAD

**Issue by aerni** [benface/tailwindcss-fluid-container#3]
I found, that the container itself doesn't have responsive classes. Only the utilities do. Is there a reason for this behavior?

**Comment by benface** [comment]
@aerni Well, the `c-container` class is a component, and components don't have variants in Tailwind, only utilities do. However, I have "cheated" on that rule before in my [`tailwindcss-triangles`](https://github.com/benface/tailwindcss-triangles/issues/1) plugin, so I agree that sometimes it makes sense... but in this case, I'm not sure. A fluid container component is nothing more than a `max-width`, auto left/right margin, and some left/right padding. I would recommend simply overriding these with the responsive container utilities when needed:

```
<div class="c-container lg:max-w-container-large lg:px-container-large">
  ...
</div>
```

Furthermore, supporting this may introduce bugs / weird behaviour when combining responsive component classes with padding/margin utilities due to the CSS order.

Let me know if the workaround above works for you, and if not, what's your use case. Thanks!

**Comment by aerni** [comment]
Ah I see. My use case is as follows:

I like how the native tailwindcss container plugin works. The `.container` class sets the `max-width `of an element to match the `min-width` of the current breakpoint. My problem with the native container plugin is, that it takes the values from `screens`. In my case I added more values to `screens` like `'4xl': 1920`, because I want to change some layout stuff at this breakpoint. However the container will then be huge! I want to restrict the max container size to something like `xl: 1200`.

With the tailwindcss-fluid-container plugin I like the ability to have responsive `padding` depending on the breakpoint. And that you can create multiple container sizes like `container-lg`. But in some cases, I'd like to change the `container-lg` to `container-md` depending on the breakpoint like `xl:container-md`.

I hope that all makes sense.

**Comment by benface** [comment]
I see, thank you for explaining! I still think responsive components would be wrong here, for two reasons:

1. Because component classes set multiple properties that are meant to be overridable by utility classes, so I'm not sure what should be expected when responsive components end up mixed with utility classes, like this for instance:

```
<div class="container md:container-md max-w-xl sm:max-w-2xl lg:max-w-3xl>
  ...
</div>
```

2. Because it could also be used to change a container's padding, not just its max-width, at different screen sizes, which would be competing with the `responsivePadding` feature (which changes the padding/margin of container components AND utilities dynamically at different screen sizes using custom properties) and possibly adding confusion as to why both exist.

Also, I'm not sure I understand how the responsive padding feature makes sense for you if you want your container to be centered with a max-width that's always smaller than the viewport's width... which by the way, kind of defeats the purpose of this plugin since it's not "fluid" anymore, haha, but why not. It's just that there's less of a reason to care about the padding if the container is centered, since there is already left/right "padding" determined by the horizontal space that's left on both sides of the container. I suppose the padding then acts as a "minimum padding" of some sort, and is only ever applied below the first breakpoint (at which point the container *is* fluid) and at exactly any of the breakpoints... but as soon as the viewport is slightly wider than a breakpoint, the left/right "document margins" become larger than that padding.

Anyway, I would like to suggest another solution: I could add a new `responsiveMaxWidth` option that works exactly like `responsivePadding`. That way, you would simply have to do something like this to achieve what you want:

```
'default': {
  maxWidth: '640px',
  padding: '15px',
  responsiveMaxWidth: {
    'md': '768px',
    'lg': '1024px',
    'xl': '1280px',
  },
},
```

And when you only want to change the max-width or padding of a specific instance of a container component (in a responsive manner or not), you can always add utility classes like I suggested in my last message.

Would that satisfy your use case?

**Comment by aerni** [comment]
Yes, you're right. I see your point that it doesn't make sense to add responsive variants to the component.

I think a `responsiveMaxWidth` option makes sense in this case.

**Comment by benface** [comment]
Done in [`v2.1.0`](https://github.com/benface/tailwindcss-fluid-container/releases/tag/v2.1.0)
